{% set name = "unsync" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unsync-{{ version }}.tar.gz
  sha256: a29e0f8952ffb0b3a0453ce436819a5a1ba2febbb5caa707c319f6f98d35f3c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - unsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-sherman/unsync
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Unsynchronize asyncio by using an ambient event loop in a separate thread.

  description: |
    unsync implements a unsync function decorator that will implement
    minimal boilerplate threading, asyncio or multiprocessing depending
    on the context. It is pure Python code with no dependencies.
  doc_url: https://asherman.io/projects/unsync.html
  dev_url: https://github.com/alex-sherman/unsync

extra:
  recipe-maintainers:
    - owenlamont
