{% set name = "unsync" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alex-sherman/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c1c585a7b5e108b89cb40ef2af99fe10ba49011a81985dfea100305c13c5b839

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - unsync

about:
  home: https://github.com/alex-sherman/unsync
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Unsynchronize asyncio by using an ambient event loop in a separate thread.

  description: |
    unsync implements a unsync function decorator that will implement
    minimal boilerplate threading, asyncio or multiprocessing depending
    on the context. It is pure Python code with no dependencies.
  doc_url: https://asherman.io/projects/unsync.html
  dev_url: https://github.com/alex-sherman/unsync

extra:
  recipe-maintainers:
    - owenlamont
